### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [69-cz-75/puchi_universe#58]
MVPリリースお疲れ様でした。
UI/UXやコード面などを中心にレビューを行いました。
ご確認をお願いいたします。

---

■まずREADMEのMVP機能が実装できているか？
=> 確認できました。LGTMです。

■UI/UX
- 博物館と美術館の違い。投稿先として分かれていますが、どういった用途分け、どういう風にユーザーは楽しめば良いのかが不透明に感じました。このサービスの使い方を明記するか、初期データを拡充して、どういったサービスなのかが直感的に分かるようにしましょう。
- スケール比較もREADMEを読まないと、どういう形で比較できるかが分からず、商品投稿のみになってしまい、サイズ感という問題解決にタッチできていないように感じました。投稿時に比較用のものも一緒に映っているように案内のポップを出すとか、注意点として明記するかなど対策を講じておくと良いかと思います。
- 画面右上に表示される「ログイン」「アカウントを作成」も左側のハンバーガーメニューから選択できるため、謎に表示されているように感じました。右上の表示は削除して、全て左側もしくは各ページで遷移できる導線を用意するかなどしましょう。
- アカウント作成に関して言うと、ユーザー名がパスワードの次に入力する形を取っていますが、パスワード確認用のフォームかと勘違いを起こしてしまいました。メールアドレス、ユーザー名にはplaceholderを設けて、何を入力するものなのかが伝わるようにしましょう。
- 画像の複数投稿もどういった使い方をすれば複数投稿できるのかが分からない可能性があります。現に他の講師から複数画像投稿ができないとの意見が挙がっておりました。複数同時アップ・1枚1枚アップした場合はそれがアップされたことが分かるように小さなプレビュー表示をして、キャンセルしたい場合は、✗ボタンを押すと消えるようにするなど、ユーザーが迷わない工夫を行いましょう。（古い記事のため、イメージの参考まで https://qiita.com/gyu_outputs/items/bae2204f8a40ff1d2d37 ）
- 初期データが少ないためか、もしくはサービス内で使い方の説明が無いためか、初見のユーザーには何をするサービスなのかが分かりにくいものになっているように感じました。上記にも記載しましたがデータの拡充もしくはサービスの使い方が分かるようにポップアップのヘルプ表示をしたりしましょう（チュートリアルとかコーチマークと呼ばれるものをイメージ： https://gihyo.jp/design/serial/01/ui-design-unsung/0029 ）

■コード・技術
- Rubocopを通すようにしましょう。
- 技術をアピールするには、その素材が少ないため、Webアプリボード内にある「Webサービスの高度な機能について」の中から機能実装のヒントを探しましょう。（マルチ検索・オートコンプリートなどが良いかと思われます）
- マルチ検索・オートコンプリートが優先ではありますが、その他にもプラス材料として、コメント、フォロー 、いいねがされたタイミングで通知がされる機能も検討してみてください。（「Webサービスの高度な機能について」の記載もご参考に）

---

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに修正完了までのスケジュール・本リリース日のスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by 69-cz-75** [comment]
@Tsuchiya2 
MVPレビューありがとうございます。
レビューを元にissueを作成致しました。
修正完了は2月中、本リリースは4月中を目標に実装したいと思っています。
[![Image from Gyazo](https://i.gyazo.com/3a8ff1ed8bc3cb755cd34cf520b62206.png)](https://gyazo.com/3a8ff1ed8bc3cb755cd34cf520b62206)
